config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :passengers, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
    scope '(:locale)', locale:/en|cn/ do 
      root 'trains#home'
      get SecureRandom.urlsafe_base64+'/trains'  => 'trains#result', as: :trains 
      
      resource :train_class , only:[:show],path: SecureRandom.urlsafe_base64+'/train_class'
      
       resource :reservation , only:[:show],path: SecureRandom.urlsafe_base64+'/reservation'
       resource :cart, only: [:show, :create]
       resources :cart_items, only: [:create,:destroy]
       resource :purchases, only:[:show] , as: :purchases do
            collection do
              get :open_orders
              get :completed_orders
              get :all_orders
            end   
          end  
       
       post '/payment' => 'carts#payment', as: :payment 
    end
   
#   #errors path redirection
    match "*path", to: "errors#not_found", via: :all
    match "*path", to: "errors#internal_server_error", via: :all
end

app/models/train.rb
class Train < ApplicationRecord
 validates :start_station_id, :end_station_id,:arrival_time, :depature_time,
            :destination,:destination_time,:end_station_time, :frequency, :train_type,
            :train_number, :train_name, presence: true
            
            
    belongs_to :from_station, class_name: 'Station', foreign_key: 'start_station_id'
  belongs_to :to_station, class_name: 'Station', foreign_key: 'end_station_id'
  
  has_many :train_classes, :dependent => :destroy
    accepts_nested_attributes_for :train_classes, :allow_destroy => true 
    
    
  before_save :titleize_all
  
  
  def self.search(from, to)
    where(start_station_id: from, end_station_id: to)
  end
  
  
  private 
    
  def titleize_all
        
    
    destination.titleize 
    frequency.titleize 
    train_type.titleize 
    train_name.titleize 
     
  end    
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  include DateCheckerHelper
  def home
    @train = Train.new
    @stations = Station.all.map { |station| [station.name, station.id] }
    # @travle_day = params[:traveling]
    @passengers = [1,2,3,4,5,6,7,8,9,10]
    
    @destinations = PopularDestination.all
    
    
  end

  def result
    
    
    if params[:train].nil?
      render home
    end
    
    if !params[:train].nil?
      @from = params[:train][:from_station]
      @to = params[:train][:to_station]
     
    # @travel_day_select = params[:train][:traveling]
      @passengers_select = params[:train][:passengers]
      
     
      @trains = Train.search(@from, @to)

      respond_to do |format|
        format.html
        format.js
      end
    end 
    
    
   @train = @trains.find_by(params[:id])
    
    
    
    if date_valid
      redirect_to root_path, alert: "Invalid Date"
      puts "manually changed to invalid date - should return to home page"
    end 
    
    
    
    
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_popular.html.erb
<div class="pop-destinations">
  <div class="hrd cded-list">
    <div class="row">
      <div class="col-md-12">
        <!--<div class="row">-->
          <%unless @destinations.nil?%>
            <%@destinations.each do |d|%>
              <div class="row">
                <div class="col-md-6">
                  <div class="des-itm">
                    <div class="des-img">
                      <%#=image_tag(thumb)%>
                    </div>
                  </div>
                </div>
              </div>
            <%end%>
          <%end%>
        <!--</div>-->
      </div>
    </div>
  </div>
</div>

app/views/trains/home.html.erb
<script src="assets/calander.js" type="text/javascript"></script>
<!--<div class="landing-section">-->
  <div class="display_area_section _display_section">
    <div class="container">
      <div class="frm-booking-tble">
        <div class="bking-frm">
          <%=form_for @train, method: :get do |f|%>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 col-xl-3  -frm-name-header-col">
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <h3 class="frm-head">
                      find & book  your train
                    </h3>
                  </div>
                </div>
                
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 -frm-pickup-opt-col">
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 -frm-pickup-opt-col">
                    <div class="form-group">
                       <%= f.label (t "home_form.depature") ,  :class => 'form-container-item-label' %> </br>
                       <%= f.select(:from_station, @stations, {selected: @from}, { id: '_station'}) %>
                    </div>
                  </div>
                  
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 -frm-pickup-opt-col">
                    <div class="form-group">
                       <%= f.label (t "home_form.arrival"), {:class => 'form-container-item-label'} %> </br>
                       <%= f.select(:to_station, @stations, {selected: @to}, { id: '_station'}) %>
                    </div>
                  </div>
                  
                </div>
                
                <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 -frm-pickup-opt-col">
                    <div class="form-group">
                       <%= f.label (t "home_form.outbound"), {:class => 'form-container-item-label'} %> </br>
                       <input type="text" id="outbound" name="outbound" class="datepicker" readonly='true' required= "true"  placeholder="dd/mm/yyyy">
                    </div>
                  </div>
                  
                  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 -frm-pickup-opt-col">
                    <div class="form-group">
                       <%= f.label (t "home_form.passengers"), {:class => 'form-container-item-label'} %> </br>
                       <%= f.select(:passengers, @passengers, {selected: @passengers_select}, { id: 'adult_select'}) %>
                    </div>
                  </div>
                  
                </div>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 col-xl-3 btn-col">
                <div class="btns-frm">
                  <%= f.submit (t "home_form.submit"), id: 'search-btn', class: 'btn btn-info'%>
                </div>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
  <%=render "popular"%>
<!--</div>-->

app/views/trains/result.html.erb
<div class="display_area_section  _display_section">  
  <div class="container">
    <%unless @trains.nil?%>
      <% if @trains.empty?%>
        <div class="info_msg-no-trains">
          <h6 class='text-center'> No Train(s) found on this route . Please try another <%=link_to 'route',root_path%> </h6>
        </div>
      <%else%>
        <%=form_tag train_class_path, method: :get do%>
          <div class="row">
            <div class="col-md-12 col-lg-9">
              <div class="gn-inf-holder">
                <div class="gn-inf">
                  <h6 class="text-uppercase text-left text-muted ot-trn-txt"><%=t "train_results.out"%></h6>
                  <h6 class="ot-date-shw"><%=params[:outbound].to_date.to_formatted_s(:long_ordinal)%></h6>
                  <div class="frm-with-cde">
                    <span>
                      <p class="frm-with-cde-txt">
                        <strong class="trn-st-nme"><%=@train.from_station.name%></strong>
                        <abbr class="code-class"title="<%=@train.from_station.name%>">(<%=@train.from_station.station_code%>)</abbr> to 
                        <strong class="trn-st-nme"><%=@train.to_station.name%></strong>
                        <abbr class="code-class" title="<%=@train.to_station.name%>">(<%=@train.to_station.station_code%>)</abbr>
                        
                      </p>
                    </span>
                  </div>
                </div>
              </div>
              <% @trains .each do |t|%>
                <div class="tkt-holder" id="tkt-holder-id">
                  <div class="tkt-tme-sta text-center">
                    <div class="st-code">
                      <abbr title="<%=t.from_station.name%>"><h6 class="sd-cd-txt"><%=t.from_station.station_code%></h6></abbr>
                    </div>
                    <div class="time">
                      <h6><%=t.arrival_time.strftime("%H:%m")%></h6>
                    </div>
                    <div class="pointer-down">
                      <i class="fa fa-arrow-down down-point" aria-hidden="true"></i>
                    </div>
                    <div class="st-code">
                      <abbr title="<%=t.to_station.name%>"><h6 class="sd-cd-txt"><%=t.to_station.station_code%></h6></abbr>
                    </div>
                    <div class="time">
                      <h6><%=t.end_station_time.strftime("%H:%m")%></h6>
                    </div>
                  </div>
                  <div class="tkt-train-price-sel text-center">
                    
                    <%=t.train_type%>
                    <br>
                    <%=radio_button_tag(:train_id, t.id) %>
                  </div>
                </div>
              <%end%>
            </div>
            <div class="col-md-12 col-lg-3">
              <div class="cd-inf-holder">
                <div class="cd-inf-box">
                  
                  <div class="cd-btn-section text-center">
                    <%= hidden_field_tag :outbound,  Date.parse(params[:outbound]).strftime("%d/%m/%Y")%>  
                   <%= hidden_field_tag :passenger_qty, params[:train][:passengers].to_i, min:1, max: 10%>
                    <%= submit_tag("Continue" , class: 'btn btn-block ' , id: 'order-btn') %>
                  </div>
                </div>
                 <div class="cd-inf-al-inf">
                  <div class="cd-inf-al-inf-section">
                    <h6 class="ot-date-shw"><%=params[:outbound].to_date.to_formatted_s(:long_ordinal)%></h6>
                    <div class="frm-with-cde">
                    <span><p class="frm-with-cde-txt"><strong class="trn-st-nme"><%=@train.from_station.name%></strong> <st_code class="code-class">(<%=@train.from_station.station_code%>)</st_code> to <strong class="trn-st-nme"><%=@train.to_station.name%></strong> <st_code class="code-class">(<%=@train.to_station.station_code%>)</st_code></p></span>
                    <h6 class="ot-date-shw"><%=params[:train][:passengers].to_i%> x  <%= t "train_results.button_info_passengers"%></h6>
                  </div>
                  
                  </div>
                </div>
              </div>
            </div>
          </div>  
          <%end%>
        <%end%>
      <%end%>   
    
  </div>
</div>  
 
 
 
 