config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :passengers, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
    scope '(:locale)', locale:/en|cn/ do 
      root 'trains#home'
      get SecureRandom.urlsafe_base64+'/trains'  => 'trains#result', as: :trains 
      
      resource :train_class , only:[:show],path: SecureRandom.urlsafe_base64+'/train_class'
      
       resource :reservation , only:[:show],path: SecureRandom.urlsafe_base64+'/reservation'
       resource :cart, only: [:show, :create]
       resources :cart_items, only: [:create,:destroy]
       resource :purchases, only:[:show] , as: :purchases do
            collection do
              get :open_orders
              get :completed_orders
              get :all_orders
            end   
          end  
       
       post '/payment' => 'carts#payment', as: :payment 
    end
   
#   #errors path redirection
    match "*path", to: "errors#not_found", via: :all
    match "*path", to: "errors#internal_server_error", via: :all
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_passenger!
  def show
      @my_cart =current_passenger.cart_items
      @my_purchases = @my_cart.joins(:cart).where('carts.status'=> "purchased").paginate(page: params[:page], per_page: 3)
  
  end
  
  def all_orders
    @my_cart =current_passenger.cart_items
    @my_purchases = @my_cart.joins(:cart).where('carts.status'=> "purchased").paginate(page: params[:page], per_page: 3)
    render action: :show
    
  end  
  
  def open_orders
    @my_cart =current_passenger.cart_items
    @my_purchases = @my_cart.joins(:cart).where('carts.status'=> "purchased", "order_state" => "placed").paginate(page: params[:page], per_page: 3)
    render action: :show
  end
  
  def completed_orders
    @my_cart =current_passenger.cart_items
    @my_purchases = @my_cart.joins(:cart).where('carts.status'=> "purchased", "order_state" => "Deliverd").paginate(page: params[:page], per_page: 3)
    render action: :show
  end  
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/show.html.erb
<div class="container purchase_container _display_section  display_area_section">
  
  
  
  
  <div class="ps-inf-holder">
    <div class="ps-inf">
      <h5 class="ps-inf-shw"><%#=t "reservations.passenger_information"%>Your purchase histroy</h5>
    </div>
  </div>
  <div class="col-md-12 col-lg-12">
    <div class="row">
      <div class="col-md-6 col-lg-6 left-sort">
        <div class="ps-inf-holder-sort">
          <div class="ps-inf">
            <div class="order_scope">
              <i class="fa fa-sliders" aria-hidden="true"></i>
              <ul class="ul_list_mi_or list-inline text-center">
                <li class="li_sort list-inline-item"><%=link_to (t ".all"), all_orders_purchases_path%></li> |
                <li class="li_sort list-inline-item"><%=link_to (t".open"),open_orders_purchases_path%></li> |
                <li class="li_sort list-inline-item"><%=link_to (t".completed"),completed_orders_purchases_path%></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12 col-lg-12 ">
        <div class="ps-inf-holder-sort-profile">
          <div class="ps-inf">
            <div class="order_scope">
              <%= link_to edit_passenger_registration_path do %>
                <i class="fa fa-user-o" aria-hidden="true"></i>
                Manage Profile
              <%end%> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>  
  
  
  <%@my_purchases. each do |cart_item|%>
    
    <div class="tkt-holder-crt" id="tkt-holder-id">
      <div class="tkt-tme-sta-crt text-left">
        <div class="st-code">
          <h6 class="sd-cd-txt-small"><%=cart_item.train_class.train.from_station.name%> to</h6> 
        </div>
        <div class="st-code-crt-bg">
          <strong><h5 class="sd-cd-txt-crt-big"><%=cart_item.train_class.train.to_station.name%></h5></strong>
        </div>
        <div class="st-code">
          <h6 class="sd-cd-txt-crt"><%=cart_item.outbound.to_date.to_formatted_s(:long_ordinal)%></h6>
        </div>
        <div class="st-code-crt-bg-time">
          <span>
            <strong><h5 class="ot-date-shw-crt"><%=cart_item.train_class.train.arrival_time.strftime("%H:%m")%></h5>
            <i class="fa fa-long-arrow-right ppt-arrw-crt" aria-hidden="true"></i>
            <h5 class="ot-date-shw-ppt-crt"><%=cart_item.train_class.train.end_station_time.strftime("%H:%m")%></h5></strong></span>
            
            <h6 class="crt-pass"><%=cart_item.passenger_qty%> x Passenger(s)</h6>
            <h6 class="crt-pass-train "><%=cart_item.train_class.train.train_type%></h6>
            
        </div>
        
      </div>
      <div class="tkt-train-price-sel-crt text-center">
        <%unless cart_item.train_class.name == "standard"%>
          <h6 class="ot-date-shw-crt-highlight"><%=cart_item.train_class.name%></h6>
        <%else%>
          <h6><%=cart_item.train_class.name%></h6>
        <%end%>
        <div class="t-cls-amt-bx text-center">
          <h5 class="t-cls-amt"><%=pounds(cart_item.train_class.price * cart_item.passenger_qty)%></h5>
        </div>
        <br>
        <%=cart_item.order_state%>
      </div>
    </div>     
  <%end%>
  
</div>  

<div class="paginate">
  <%= will_paginate @my_purchases, list_classes: %w(pagination ),aria_label:"Page Navigation",previous_label: '&laquo;',next_label: '&raquo;'   %>
</div>