config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :passengers, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
    scope '(:locale)', locale:/en|cn/ do 
      root 'trains#home'
      get SecureRandom.urlsafe_base64+'/trains'  => 'trains#result', as: :trains 
      
      resource :train_class , only:[:show],path: SecureRandom.urlsafe_base64+'/train_class'
      
       resource :reservation , only:[:show],path: SecureRandom.urlsafe_base64+'/reservation'
       resource :cart, only: [:show, :create]
       resources :cart_items, only: [:create,:destroy]
       resource :purchases, only:[:show] , as: :purchases do
            collection do
              get :open_orders
              get :completed_orders
              get :all_orders
            end   
          end  
       
       post '/payment' => 'carts#payment', as: :payment 
    end
   
#   #errors path redirection
    match "*path", to: "errors#not_found", via: :all
    match "*path", to: "errors#internal_server_error", via: :all
end

app/models/cart.rb
class Cart < ApplicationRecord
  require 'securerandom'  

  has_many :cart_items
  before_create :set_cart_status
  before_create :set_uuid 
  
  before_save :update_subtotal
  
  #after_update :email_purchase

  def subtotal
    cart_items.collect { |oi| oi.valid? ? (oi.passenger_qty * oi.unit_price) : 0 }.sum
  end
  
  # def email_purchase
  #   if status_changed? && status == "purchased"
  #     ReceiptMailer.purchase_order(self).deliver_now
      
      
  #   end
  #end  

  
private
  def set_cart_status
    self.status = "pending"
    self.delivery_status = "placed"
    
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
  
  def set_uuid
    self.uuid = SecureRandom.hex(3)
  end  
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token
    def show
        @cart_items = current_order.cart_items
        @cart_item = current_order.cart_items.find_by(params[:id])
    end
    
    def payment
      # @cart_items = current_order.cart_items
    Cart.find(session[:cart_id])
    result = Braintree::Transaction.sale(
              amount: current_order.subtotal,
              payment_method_nonce: params[:payment_method_nonce],
              
              :options => {
                :submit_for_settlement => true},
             
                  
              )
    response = {:success => result.success?}          
    if result.success?
      #puts "Thank you for your purchase, success!: #{result.transaction.id}"
      response[:transaction_id] = result.transaction.id
      current_order.update(status: "purchased")
      
      ReceiptMailer.purchase_order(current_passenger, current_order).deliver_now # sending proof of purchase email to customer
       
       OrderAlertAdminMailer.purchase_notification.deliver_now 
       
      redirect_to root_path, notice: "Thank you for booking, Please check your email for invoice"
      session.delete(:cart_id)
      
    elsif result.transaction
      puts "Something went wrong while processing your transaction.Payment was not sucessful!. Please try again!"
      puts "code: #{result.transaction.processor_response_code}"
      puts "code: #{result.transaction.processor_response_text}"
      error_messages = result.errors.map { |error| "Error: #{error.code}: #{error.message}" }
      # flash[:error] = error_messages
      redirect_to cart_path, alert: "something went wrong, your transcations was not successful!"
      
      
      response[:error] = result.transaction.processor_response_text
      
    else
      p result.errors
      
      response[:error] = result.errors.inspect
      redirect_to cart_path, alert: result.errors.map { |error| "#{error.message}" }
    end
     #render :json => response  
    end    
        
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_shopping_cart.html.erb
<script>
  $.ajaxSetup({ cache: false });

window.onpopstate = function(event) {
    if(event && event.state) {
        location.reload()
    }
}

</script>

<div class=" display_area_section_crt  _display_section">  
  <div class="crt_dis_section">
    
     <% if !@cart_item.nil? && @cart_item.errors.any?  %>
      <div class="alert alert-danger">
        <ul>
        <% @cart_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
      <% if @cart_items.size == 0 %>
        <div class="info_msg-no-trains">
          <h6 class='text-center'> <%=t "cart_pay.empty_cart_front"%><%= link_to (t "cart_pay.empty_cart_middle_link"), root_path %> <%=t "cart_pay.empty_cart_back"%></h6>
        </div>
      <%else%>
      <div class="itm-review-message">
        <div class="review-message-text">
          <%if current_order.cart_items.size > 1%>
          <h4>Review your <%=current_order.cart_items.size%> journeys</h4>
          <%else%>
          <h4>Your trip to <strong><%=@cart_item.train_class.train.to_station.name%></strong> </h4>
          <%end%>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8 ">
          <% @cart_items.each do |cart_item| %>
            <%= form_for cart_item, remote: true do |f| %>
              <div class="tkt-holder-crt" id="tkt-holder-id">
                <div class="tkt-tme-sta-crt text-left">
                  <div class="st-code">
                    <h6 class="sd-cd-txt-small"><%=cart_item.train_class.train.from_station.name%> to</h6> 
                  </div>
                  <div class="st-code-crt-bg">
                    <strong><h5 class="sd-cd-txt-crt-big"><%=cart_item.train_class.train.to_station.name%></h5></strong>
                  </div>
                  <div class="st-code">
                    <h6 class="sd-cd-txt-crt"><%=cart_item.outbound.to_date.to_formatted_s(:long_ordinal)%></h6>
                  </div>
                  <div class="st-code-crt-bg-time">
                    <span>
                      <strong><h5 class="ot-date-shw-crt"><%=cart_item.train_class.train.arrival_time.strftime("%H:%m")%></h5>
                      <i class="fa fa-long-arrow-right ppt-arrw-crt" aria-hidden="true"></i>
                      <h5 class="ot-date-shw-ppt-crt"><%=cart_item.train_class.train.end_station_time.strftime("%H:%m")%></h5></strong></span>
                      
                      <h6 class="crt-pass"><%=cart_item.passenger_qty%> x Passenger(s)</h6>
                      <h6 class="crt-pass-train "><%=cart_item.train_class.train.train_type%></h6>
                      
                  </div>
                  
                </div>
                <div class="tkt-train-price-sel-crt text-center">
                  <%unless cart_item.train_class.name == "standard"%>
                    <h6 class="ot-date-shw-crt-highlight"><%=cart_item.train_class.name%></h6>
                  <%else%>
                    <h6><%=cart_item.train_class.name%></h6>
                  <%end%>
                  <div class="t-cls-amt-bx text-center">
                    <h5 class="t-cls-amt"><%=pounds(cart_item.train_class.price * cart_item.passenger_qty)%></h5>
                  </div>
                  <br>
                  <%= link_to cart_item, method: :delete, remote: true do %>
                      <i class="fa fa-trash-o" aria-hidden="true" id="trash"></i>  
                  <%end%>
                </div>
              </div>  
            <%end%>
          <%end%>
        </div>
        <div class="col-lg-4">
          <div class="crt-pay holder">
            <%= form_tag payment_path , id: "cardForm" do %>
              <div class="brain-render">
                <%=render "layouts/braintree_form"%>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/carts/payment.html.erb
<div class="container display_area_section _display_section">
    
    
     <h3 class"text-center">Something went wrong ! your payment wasn't not successful. Please try again</h3>
 
</div>

app/views/carts/show.html.erb
<div class="display_area_section _display_section">
  <div class="container">
    <div class="shopping-cart">
      <%= render "shopping_cart" %>
    </div>
  </div>
</div>  