config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :passengers, :controllers => {:passwords => "passwords" , :registrations => "registrations"} 
    scope '(:locale)', locale:/en|cn/ do 
      root 'trains#home'
      get SecureRandom.urlsafe_base64+'/trains'  => 'trains#result', as: :trains 
      
      resource :train_class , only:[:show],path: SecureRandom.urlsafe_base64+'/train_class'
      
       resource :reservation , only:[:show],path: SecureRandom.urlsafe_base64+'/reservation'
       resource :cart, only: [:show, :create]
       resources :cart_items, only: [:create,:destroy]
       resource :purchases, only:[:show] , as: :purchases do
            collection do
              get :open_orders
              get :completed_orders
              get :all_orders
            end   
          end  
       
       post '/payment' => 'carts#payment', as: :payment 
    end
   
#   #errors path redirection
    match "*path", to: "errors#not_found", via: :all
    match "*path", to: "errors#internal_server_error", via: :all
end

app/views/layouts/_braintree_form.html.erb
<div class="panel">
  <header class="panel__header">
    <h3 class="text-center"><%= t "cart_pay.payment_details"%></h3>
  </header>
  <div class="panel__content">
    <div class="paypl">
      <div id="paypal-button"></div>
      <hr>
    </div>
    
   <!--<div id="dropin-container"></div>-->
    <div class="cards_forma">  
      <div class="textfield--float-label">
        <label class="hosted-field--label" for="card-number"><span class="icon">
         <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M0 0h24v24H0z" fill="none"/><path d="M20 4H4c-1.11 0-1.99.89-1.99 2L2 18c0 1.11.89 2 2 2h16c1.11 0 2-.89 2-2V6c0-1.11-.89-2-2-2zm0 14H4v-6h16v6zm0-10H4V6h16v2z"/></svg></span> Card Number 
        </label>
        <div id="card-number" class="hosted-field"></div>
      </div>
  
      <div class="textfield--float-label-expire">
  
        <label class="hosted-field--label" for="expiration-date">
           <span class="icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M9 11H7v2h2v-2zm4 0h-2v2h2v-2zm4 0h-2v2h2v-2zm2-7h-1V2h-2v2H8V2H6v2H5c-1.11 0-1.99.9-1.99 2L3 20c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 16H5V9h14v11z"/></svg>
         </span> 
          Expire</label>
        <div id="expiration-date" class="hosted-field"></div>
      </div>
  
  
      <div class="textfield--float-label-ccv">
        <label class="hosted-field--label" for="cvv">
          <span class="icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/></svg>
            </span>
            CVV</label>
        <div id="cvv" class="hosted-field"></div>
      </div>
    </div>
  </div>
  <footer class="panel__footer">
    <div class="current_subt_t">
      <span class="pull-left current_subt_t_tot"><%= t "cart_pay.total"%>:</span>
      <span class="pull-right current_subt_t_dis_tot"><%=number_to_currency current_order.subtotal%></span>
      <input type="hidden" id="nonce" name="payment_method_nonce" />
      <button type="submit" class="btn btn-success btn-block" id="submit_button"  ><%=t "cart_pay.pay_finish"%></button>
    </div> 
  </footer>
</div>

<script>
var form = document.querySelector('#cardForm');
var nonce = document.querySelector('#nonce');
var submitButton = document.querySelector('#submit-button');

braintree.client.create({
  authorization: '<%=Braintree::ClientToken.generate%>'
}, 

function (err, clientInstance) {
  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '16px',
        'font-family': 'roboto, verdana, sans-serif',
        'font-weight': 'lighter',
        'color': 'black'
      },
      ':focus': {
        'color': 'black'
      },
      '.valid': {
        'color': 'black'
      },
      '.invalid': {
        'color': 'black'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '1111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '111'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: 'MM/YY'
      }
    }
  },function(err, hostedFieldsInstance) {
    if (err) {
      console.error(err);
      return;
    }
    
    
    hostedFieldsInstance.on('focus', function (event) {
      var field = event.fields[event.emittedBy];
      
      $(field.container).next('.hosted-field--label').addClass('label-float').removeClass('filled');
    });
    
    // Emulates floating label pattern
    hostedFieldsInstance.on('blur', function (event) {
      var field = event.fields[event.emittedBy];
      
      if (field.isEmpty) {
        $(field.container).next('.hosted-field--label').removeClass('label-float');
      } else if (event.isValid) {
        $(field.container).next('.hosted-field--label').addClass('filled');
      } else {
        $(field.container).next('.hosted-field--label').addClass('invalid');
      }
    });
    
    hostedFieldsInstance.on('empty', function (event) {
      var field = event.fields[event.emittedBy];

      $(field.container).next('.hosted-field--label').removeClass('filled').removeClass('invalid');
    });
    
    hostedFieldsInstance.on('validityChange', function (event) {
      var field = event.fields[event.emittedBy];

      if (field.isPotentiallyValid) {
        $(field.container).next('.hosted-field--label').removeClass('invalid');
      } else {
        $(field.container).next('.hosted-field--label').addClass('invalid');  
      }
    });
    
    $('#cardForm').submit(function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (err, payload) {
        if (err) {
          console.error(err);
          return;
        }

        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
    });
  });
  
 braintree.paypalCheckout.create({
    client: clientInstance
  }, function (paypalCheckoutErr, paypalCheckoutInstance) {

    // Stop if there was a problem creating PayPal Checkout.
    // This could happen if there was a network error or if it's incorrectly
    // configured.
    if (paypalCheckoutErr) {
      console.error('Error creating PayPal Checkout:', paypalCheckoutErr);
      return;
    }

    // Set up PayPal with the checkout.js library
    paypal.Button.render({
      env: 'sandbox', // or 'sandbox'
      commit: true, // This will add the transaction amount to the PayPal button

      payment: function () {
        return paypalCheckoutInstance.createPayment({
          flow: 'checkout', // Required
          amount: '<%=current_order.subtotal%>', // Required
          currency: 'USD', // Required
          
        });
      },

      onAuthorize: function (data, actions) {
        return paypalCheckoutInstance.tokenizePayment(data)
          .then(function (payload) {
            // Submit `payload.nonce` to your server
        
        $.ajax({
          method: "POST",
          url: "/payment",
          data: { payment_method_nonce: payload.nonce }
        })
      
            
          });
      },

      onCancel: function (data) {
        console.log('checkout.js payment cancelled', JSON.stringify(data, 0, 2));
      },

      onError: function (err) {
        console.error('checkout.js error', err);
      }
    }, '#paypal-button').then(function () {
      // The PayPal button will be rendered in an html element with the id
      // `paypal-button`. This function will be called when the PayPal button
      // is set up and ready to be used.
    });

  

});

  
});
</script>

app/views/layouts/_cart_text.html.erb
<%= link_to  cart_path do%>
  <div class="cart-mnu-all-itms">
    <div  class="cart-count" >
      <ct class="current-count"><%=current_order.cart_items.size%></ct>
    </div>
    <i class="fa fa-shopping-cart cart-img" aria-hidden="true"></i>
    <div class="cart-tot">
      <%=pounds( current_order.subtotal)%>
    </div>
  </div>
<%end%>
   

app/views/layouts/_drop_down_nav.html.erb
<div class="log_wish_etc_con">
  <div class="container _drop_con">
   <div class="drop_down_log_wish">
    <ul class="drop_down_log_wish_ul">
      <li class ="drop_down_log_wish_list"><span class="glyphicon glyphicon-user"></span>
        <% if passenger_signed_in?%>
          <%=t "nav_bar_top.hello"%>,<%=current_passenger.first_name%> 
           <%= link_to "Exit", destroy_passenger_session_path, :method => 'delete', :class => "sign_in_out"  %>
          <%else%>
           <%= link_to "Login or Register", new_passenger_session_path%> 
        <%end%>
      </li>
      <li class ="drop_down_log_wish_list_help"><i class="fa fa-cogs" aria-hidden="true"></i></i><%=link_to "Manage Account",edit_passenger_registration_path, :class => "wish_link_path"%></li>
      <li class ="drop_down_log_wish_list"><i class="fa fa-heart" aria-hidden="true"></i><%=link_to "Bookings",purchases_path, :class => "wish_link_path"%></li>
      <li class ="drop_down_log_wish_close"><i class="fa fa-times" aria-hidden="true" role="button" area-pressed="false"></i></li>
    </ul>
   </div>
  </div>
</div>

app/views/layouts/_errors_notifications.html.erb
<div class="notice-wrapper">
  <% if flash[:error] %>
    <div class="show notice error notice-error">
      <span class="notice-message">
        <%= alert_string(flash[:error]) %>
      </span>
    </div>
  <% end %>
</div>

app/views/layouts/_mobile_menu.html.erb
<nav role ="navigation" id="mob_nav" class="site_nav mobile_na">
  <div class="container _mob_cont">
    <button class="mob_nav_toggle mob-nav-top">Menu</button>
    <ul class="mob_nav_ul menu_links">
      <li class="mob_nav_ul_child">
        <%= link_to_unless_current "English", locale: "en"%> |  <%= link_to_unless_current "Chinese", locale: "cn" %>
      </li>
      
      
      <li class="mob_nav_ul_child">
        <%#=link_to "Login or register", "#"%>
        
        <% if passenger_signed_in?%>
          
          <%=t "nav_bar_top.hello"%>,<%=current_passenger.first_name%> 
          <%= link_to "Exit", destroy_passenger_session_path, :method => 'delete', :class => "sign_in_out"  %>
          <%else%>
          
          <%= link_to "Login or Register", new_passenger_session_path%> 
        <%end%>
        <span class="glyphicon glyphicon-user" id=mob-nav_icn></span>
        <i class="fa fa-angle-down" aria-hidden="true"></i>
      </li>
      
      <li class="mob_nav_ul_child">
        <%=link_to "Bookings",purchases_path, :class => "wish_link_path"%>
        <i class="fa fa-heart-o" aria-hidden="true" id=mob-nav_icn></i>
        
      </li>
      
      <li class="mob_nav_ul_child">
        <%=link_to "Manage Account",edit_passenger_registration_path, :class => "wish_link_path"%>
        <i class="fa fa-cogs" aria-hidden="true" id=mob-nav_icn></i>
        
      </li>
      
    </ul>
    
</nav>

app/views/layouts/_nav.html.erb
<div class="topnav">
  <div class="container">
    <div class="menue-holder">
      <div class="lang-opts">
        <%= link_to_unless_current "English", locale: "en"%> |  <%= link_to_unless_current "Chinese", locale: "cn" %>
      </div>
      <div class="logo-box">
        <%=link_to image_tag("logo.png", alt:"logo", :width => 75),root_path %>
      </div>
      <div class="desk-log-opts">
        <i class="fa fa-ellipsis-v desk-log" aria-hidden="true" role ="button" area-presses="false"></i>
        <div class="_anim_bar">
          <div class="bar1"></div>
          <div class="bar2"></div>
          <div class="bar3"></div>
        </div>
      </div>
      
      <div class="cart-box">
        <%#if passenger_signed_in?%>
          <strong class="cart-text"><%= render 'layouts/cart_text' %></strong>
        <%#end%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carriage-Lanka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
    <script src="https://js.braintreegateway.com/web/3.23.0/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.23.0/js/hosted-fields.min.js"></script>
    <script src="https://www.paypalobjects.com/api/checkout.js" data-version-4 log-level="warn"></script>
    <script src="https://js.braintreegateway.com/web/3.23.0/js/paypal-checkout.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.23.0/js/data-collector.min.js"></script>
  </head>

  <body>
    <%=render 'layouts/nav'%>
    <%=render "layouts/drop_down_nav"%>
    <%=render "layouts/mobile_menu"%>
    
    <%= yield %>
    <%= content_tag :body, class: "#{controller_name}-#{action_name}" do %>
        <!-- set background only for the home page -->
    <% end %>
    <div class="container">
      <% if notice%>
      <div id="notice_wrapper">
       <i class="fa fa-check-circle-o notice-correct" aria-hidden="true"></i>
       <p class= "notice">  <%=notice%></p>
      </div>
      <%elsif alert%>
       <div id="error_wrapper">
        <i class="fa fa-exclamation-circle notice-error" aria-hidden="true"></i>
        <p class= "alert"> <%=alert%></p>
      </div>
    <%end%>
    </div>
    
    
  </body>
</html>